name: Manual Release Trigger

on:
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force create release even if tag exists'
        required: false
        default: false
        type: boolean

jobs:
  manual-release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get app version
      id: app_version
      run: |
        APP_VERSION=$(plutil -p Xamrock.app/Contents/Info.plist | grep CFBundleShortVersionString | cut -d'"' -f4)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_OUTPUT
        echo "App version: $APP_VERSION"

    - name: Create release tag
      run: |
        APP_VERSION="${{ steps.app_version.outputs.APP_VERSION }}"
        FORCE_RELEASE="${{ github.event.inputs.force_release }}"

        echo "Creating release for version: $APP_VERSION"

        # Check if tag exists
        if git rev-parse "$APP_VERSION" >/dev/null 2>&1; then
          if [ "$FORCE_RELEASE" = "true" ]; then
            echo "Tag exists but force_release is true, deleting and recreating..."
            git tag -d "$APP_VERSION" || true
            git push origin ":refs/tags/$APP_VERSION" || true
          else
            echo "❌ Tag $APP_VERSION already exists. Use force_release option to override."
            exit 1
          fi
        fi

        # Create and push tag
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "$APP_VERSION"
        git push origin "$APP_VERSION"

        echo "✅ Created and pushed tag: $APP_VERSION"
        echo "🚀 Release workflow will trigger automatically!"