name: Create Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get version from app bundle
      id: get_version
      run: |
        VERSION=$(plutil -p Xamrock.app/Contents/Info.plist | grep CFBundleShortVersionString | cut -d'"' -f4)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "App version: $VERSION"

    - name: Create distribution archive
      run: |
        zip -r Xamrock-${{ steps.get_version.outputs.VERSION }}.zip Xamrock.app

    - name: Calculate SHA256
      id: sha256
      run: |
        SHA256=$(shasum -a 256 Xamrock-${{ steps.get_version.outputs.VERSION }}.zip | cut -d ' ' -f 1)
        echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
        echo "SHA256: $SHA256"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Xamrock ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Xamrock ${{ steps.get_version.outputs.VERSION }}

          ### Installation via Homebrew
          ```bash
          brew tap xamrock/xamrock-desktop
          brew install --cask xamrock
          ```

          ### Manual Installation
          1. Download the `Xamrock-${{ steps.get_version.outputs.VERSION }}.zip` file below
          2. Unzip the file
          3. Move `Xamrock.app` to your `/Applications` folder

          ### SHA256 Checksum
          ```
          ${{ steps.sha256.outputs.SHA256 }}
          ```
        files: Xamrock-${{ steps.get_version.outputs.VERSION }}.zip
        draft: false
        prerelease: false

    - name: Update Homebrew cask formula
      if: success()
      run: |
        # Update the cask file with new version and SHA256
        sed -i '' "s/version \".*\"/version \"${{ steps.get_version.outputs.VERSION }}\"/" Casks/xamrock.rb
        sed -i '' "s/sha256 \".*\"/sha256 \"${{ steps.sha256.outputs.SHA256 }}\"/" Casks/xamrock.rb

        echo "Updated cask formula:"
        echo "  Version: ${{ steps.get_version.outputs.VERSION }}"
        echo "  SHA256: ${{ steps.sha256.outputs.SHA256 }}"

    - name: Commit updated cask formula
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout main
        git add Casks/xamrock.rb
        git commit -m "Update Homebrew cask to ${{ steps.get_version.outputs.VERSION }}" || exit 0
        git push origin main